"""initial

Revision ID: ed7df405935c
Revises:
Create Date: 2026-06-13 17:51:48.665649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ed7df405935c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # users
    op.create_table(
        'users',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('totp_secret', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # excel_uploads
    op.create_table(
        'excel_uploads',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('usuario_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
        sa.Column('total_ordenes', sa.Integer(), nullable=False),
        sa.Column('ordenes_validas', sa.Integer(), nullable=False),
        sa.Column('ordenes_con_error', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )

    # ordenes (enum types are created automatically by sa.Enum when first encountered)
    op.create_table(
        'ordenes',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('excel_upload_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('cliente_nombre', sa.String(length=255), nullable=False),
        sa.Column('cliente_email', sa.String(length=512), nullable=False),
        sa.Column('cuenta_comitente', sa.String(length=256), nullable=False),
        sa.Column('cuenta_cotapartista', sa.String(length=256), nullable=False),
        sa.Column('instrumento', sa.String(length=100), nullable=False),
        sa.Column('tipo', sa.Enum('COMPRA', 'VENTA', name='tipoperacion'), nullable=False),
        sa.Column('cantidad', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('precio', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('moneda', sa.String(length=10), nullable=False),
        sa.Column('liquidacion', sa.Enum('CI', '24HS', '48HS', name='condicionliquidacion'), nullable=False),
        sa.Column('fecha_operacion', sa.DateTime(), nullable=False),
        sa.Column('dj_aplicada', sa.Boolean(), nullable=False),
        sa.Column('dj_tipo', sa.String(length=100), nullable=True),
        sa.Column('estado', sa.Enum('BORRADOR', 'APROBADO', 'ENVIADO', 'CONFIRMADO', 'ALERTA', name='estadominuta'), nullable=False),
        sa.Column('texto_minuta', sa.Text(), nullable=False),
        sa.Column('texto_editado', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['excel_upload_id'], ['excel_uploads.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )

    # audit_events
    op.create_table(
        'audit_events',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('orden_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('usuario_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('accion', sa.Enum('CREADA', 'EDITADA', 'APROBADA', 'ENVIADA', 'CONFIRMADA', 'ALERTA_GENERADA', name='accionaudit'), nullable=False),
        sa.Column('ip_origen', sa.String(length=45), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('detalle', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ),
        sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_audit_events_orden_id'), 'audit_events', ['orden_id'], unique=False)

    # dj_templates
    op.create_table(
        'dj_templates',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('nombre', sa.String(length=100), nullable=False),
        sa.Column('texto', sa.Text(), nullable=False),
        sa.Column('reglas', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('prioridad', sa.Integer(), nullable=False),
        sa.Column('activo', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nombre'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dj_templates')
    op.drop_index(op.f('ix_audit_events_orden_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('ordenes')
    op.drop_table('excel_uploads')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')

    op.execute('DROP TYPE IF EXISTS accionaudit')
    op.execute('DROP TYPE IF EXISTS estadominuta')
    op.execute('DROP TYPE IF EXISTS condicionliquidacion')
    op.execute('DROP TYPE IF EXISTS tipoperacion')
    # ### end Alembic commands ###
